version: '3.9'

services:
  db:
    image: mysql:8.1.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    volumes:
      - volumes

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ports
    environment:
      PMA_ARBITRARY: 1

volumes:
  volumes:

